FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_STRAPI_URL
ENV VITE_STRAPI_URL=$VITE_STRAPI_URL

ARG VITE_GOOGLE_BOOKS_API_KEY
ENV VITE_GOOGLE_BOOKS_API_KEY=$VITE_GOOGLE_BOOKS_API_KEY

RUN npm run build

EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host"]
